@host=http://localhost:5053

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "ja@gmail.com",
    "password": "Password123!"
}